name: Feature Request/Improvement
description: Suggest a new feature or improvements to existing ones.
labels: [ "enhancement" ]
assignees:
  - WolfyScript
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out a feature request for CustomCrafting!  
        Please describe everything as detailed as possible, so it is easier to understand.  
        Before submitting the issue please make sure, that you searched for and ensured there isn't a duplicate issue.  
        Additionally, please make sure that you are using the latest plugin version and the feature isn't already implemented!
        If you think you have a good feature request, but are not sure if you should post it, feel free to ask in the `#support` channel on [Discord](https://discord.gg/qGhDTSr)
  - type: textarea
    attributes:
      label: The Problem
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: Describe the solution you would like.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Submit issue
      description: "By submitting this issue you made sure that you,"
      options:
        - label: "searched for and ensured there isn't already an open issue regarding this,"
          required: true
        - label: "are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting)."
          required: true